CREATE TABLE IF NOT EXISTS photos (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NULL,
    caption VARCHAR(255) NULL,
    url VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)